export const CABINET_CONFIG = {
  name: "Cabinet dentaire Hakan Gumustepe",
  slogan: "Votre sourire, notre priorité",
  subtitle: "Des soins dentaires d'excellence dans un cadre moderne et rassurant. Notre équipe vous accompagne avec bienveillance pour une santé bucco-dentaire optimale.",
  address: "1 Route de Strasbourg",
  city: "Haguenau",
  zip: "67000",
  phone: "01 42 56 78 90",
  email: "contact@cabinet-dentaire-du-parc.fr",
  formspreeEndpoint: "https://formspree.io/f/mzdjppep",
  openingHours: [
    { day: "Lundi", hours: "9h00 - 19h00" },
    { day: "Mardi", hours: "9h00 - 19h00" },
    { day: "Mercredi", hours: "9h00 - 19h00" },
    { day: "Jeudi", hours: "9h00 - 19h00" },
    { day: "Vendredi", hours: "9h00 - 18h00" },
    { day: "Samedi", hours: "9h00 - 13h00" },
    { day: "Dimanche", hours: "Fermé" },
  ],
  googleMapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2627.5532285245154!2d7.779107711935066!3d48.80950497120586!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796eace2644b0f1%3A0x8214936fdab300e0!2s1%20Rte%20de%20Strasbourg%2C%2067500%20Haguenau%2C%20France!5e0!3m2!1sfr!2slv!4v1772663670399!5m2!1sfr!2slv",
  placeId: "VOTRE_PLACE_ID",
  googlePlacesApiKey: "VOTRE_GOOGLE_PLACES_API_KEY",
  doctolibEmbedUrl: "https://www.doctolib.fr/medecin-generaliste/strasbourg/selim-gumustepe",
  doctolibProfileUrl: "https://www.doctolib.fr/medecin-generaliste/strasbourg/selim-gumustepe",
  socialLinks: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
  },
  contactEmail: "contact@cabinet-dentaire-du-parc.fr",
  webhookUrl: "",
};

export const TEAM_MEMBERS = [
  {
    id: "dr-martin",
    name: "Dr. Sophie Martin",
    title: "Chirurgien-Dentiste",
    specialty: "Implantologie & Esthétique",
    bio: "Diplômée de la Faculté de Chirurgie Dentaire de Paris, le Dr Martin exerce depuis plus de 15 ans. Passionnée par l'implantologie et l'esthétique dentaire, elle place le confort et l'écoute du patient au cœur de sa pratique.",
    diplomas: ["Doctorat en Chirurgie Dentaire – Université Paris Descartes", "DU Implantologie – Université Paris Diderot", "Formation continue en esthétique dentaire"],
    approach: "Une approche douce et rassurante, avec un accent sur la communication et l'explication de chaque étape du traitement.",
    image: "female",
  },
  {
    id: "dr-dubois",
    name: "Dr. Thomas Dubois",
    title: "Chirurgien-Dentiste",
    specialty: "Parodontologie & Soins conservateurs",
    bio: "Le Dr Dubois est spécialisé en parodontologie et soins conservateurs. Son approche préventive et sa maîtrise des technologies modernes garantissent des traitements de haute qualité dans un environnement bienveillant.",
    diplomas: ["Doctorat en Chirurgie Dentaire – Université de Strasbourg", "CES Parodontologie", "Certification en dentisterie numérique"],
    approach: "Un praticien à l'écoute, privilégiant les techniques mini-invasives et la prévention pour préserver au maximum les dents naturelles.",
    image: "male",
  },
];

export const SOINS = [
  {
    id: "detartrage",
    title: "Détartrage",
    icon: "Sparkles",
    shortDesc: "Un nettoyage professionnel pour des dents saines et un sourire éclatant.",
    description: "Le détartrage est un soin essentiel pour éliminer le tartre et la plaque dentaire qui s'accumulent sur vos dents. Ce geste préventif protège vos gencives et prévient les maladies parodontales.",
    whenToConsult: "Il est recommandé de faire un détartrage au moins une fois par an, ou tous les 6 mois si vous êtes sujet à l'accumulation de tartre.",
    procedure: "Le praticien utilise un appareil à ultrasons pour retirer délicatement le tartre, suivi d'un polissage pour lisser la surface des dents.",
    duration: "30 à 45 minutes",
    comfort: "Indolore dans la majorité des cas",
    afterCare: "Éviter les aliments colorants pendant 24h. Maintenir un brossage régulier 2 fois par jour.",
  },
  {
    id: "caries",
    title: "Traitement des caries",
    icon: "Shield",
    shortDesc: "Des soins conservateurs pour traiter et prévenir les caries.",
    description: "La carie est une destruction progressive de l'émail puis de la dentine. Détectée tôt, elle se traite simplement et rapidement grâce à des techniques modernes et esthétiques.",
    whenToConsult: "Douleur au chaud ou au froid, sensibilité, tache sombre sur une dent.",
    procedure: "Après anesthésie locale, la partie cariée est retirée et remplacée par un composite de la couleur de votre dent.",
    duration: "30 minutes à 1 heure",
    comfort: "Traitement sous anesthésie locale, totalement indolore",
    afterCare: "Éviter de manger du côté traité pendant 2h. Reprendre le brossage normalement.",
  },
  {
    id: "couronnes",
    title: "Couronnes",
    icon: "Crown",
    shortDesc: "Restaurez l'esthétique et la fonction de vos dents abîmées.",
    description: "La couronne dentaire est une prothèse qui recouvre entièrement une dent fragilisée pour lui redonner sa forme, sa solidité et son esthétique naturelle.",
    whenToConsult: "Dent très abîmée, fracturée, dévitalisée, ou pour améliorer l'esthétique.",
    procedure: "La dent est préparée, une empreinte est prise (numérique), puis la couronne est fabriquée sur mesure et scellée.",
    duration: "2 séances de 45 minutes",
    comfort: "Anesthésie locale, aucune douleur pendant le soin",
    afterCare: "Pas de précautions particulières. Brossage et fil dentaire comme d'habitude.",
  },
  {
    id: "implants",
    title: "Implants dentaires",
    icon: "Wrench",
    shortDesc: "La solution durable pour remplacer vos dents manquantes.",
    description: "L'implant dentaire est une racine artificielle en titane posée dans l'os de la mâchoire. Il sert de support à une couronne, un bridge ou une prothèse. C'est la solution la plus fiable et durable.",
    whenToConsult: "Dent manquante, prothèse amovible inconfortable, souhait d'une solution fixe.",
    procedure: "Pose chirurgicale de l'implant, période de cicatrisation (2-4 mois), puis pose de la couronne définitive.",
    duration: "Chirurgie : 1h | Traitement complet : 3-6 mois",
    comfort: "Intervention sous anesthésie locale, douleurs post-opératoires très modérées",
    afterCare: "Alimentation molle pendant 1 semaine. Hygiène rigoureuse. Suivi régulier.",
  },
  {
    id: "esthetique",
    title: "Esthétique dentaire",
    icon: "Star",
    shortDesc: "Sublimez votre sourire avec nos soins esthétiques personnalisés.",
    description: "Blanchiment, facettes, alignement… Nous proposons des solutions esthétiques sur mesure pour vous offrir le sourire dont vous rêvez, en toute sécurité.",
    whenToConsult: "Dents jaunies, tachées, mal alignées, espaces entre les dents.",
    procedure: "Selon le soin : gouttières de blanchiment, pose de facettes en céramique, ou aligneurs invisibles.",
    duration: "Variable selon le traitement",
    comfort: "Traitements non invasifs à peu invasifs",
    afterCare: "Varie selon le soin. Votre praticien vous donnera des conseils personnalisés.",
  },
  {
    id: "urgences",
    title: "Urgences dentaires",
    icon: "AlertCircle",
    shortDesc: "Prise en charge rapide de vos urgences dentaires.",
    description: "Douleur intense, dent cassée, abcès… Notre cabinet assure une prise en charge rapide des urgences dentaires pour vous soulager dans les plus brefs délais.",
    whenToConsult: "Douleur aiguë, gonflement, traumatisme dentaire, saignement important.",
    procedure: "Diagnostic immédiat, soulagement de la douleur, traitement d'urgence, puis plan de soins si nécessaire.",
    duration: "30 minutes à 1 heure",
    comfort: "Priorité au soulagement de la douleur",
    afterCare: "Suivi selon le traitement réalisé. Consultation de contrôle recommandée.",
  },
  {
    id: "pedodontie",
    title: "Pédodontie",
    icon: "Baby",
    shortDesc: "Des soins adaptés et bienveillants pour les plus petits.",
    description: "La pédodontie est la spécialité dédiée aux soins dentaires des enfants. Notre approche ludique et rassurante permet aux enfants de vivre une expérience positive chez le dentiste.",
    whenToConsult: "Première visite recommandée dès 3 ans, puis suivi régulier tous les 6 mois.",
    procedure: "Examen adapté, apprentissage du brossage, soins préventifs (scellement de sillons) et curatifs si nécessaire.",
    duration: "20 à 30 minutes",
    comfort: "Approche ludique et douce, adaptée à l'âge de l'enfant",
    afterCare: "Encourager le brossage régulier et limiter les sucreries.",
  },
];

export const REVIEWS = [
  { author: "Marie L.", rating: 5, text: "Excellent cabinet ! L'équipe est très professionnelle et rassurante. Je recommande vivement.", date: "Il y a 2 semaines" },
  { author: "Pierre D.", rating: 5, text: "Dr Martin est exceptionnelle. Elle a pris le temps de tout m'expliquer et le résultat est parfait.", date: "Il y a 1 mois" },
  { author: "Isabelle R.", rating: 5, text: "Cabinet moderne et propre. L'accueil est chaleureux. Plus de peur d'aller chez le dentiste !", date: "Il y a 1 mois" },
  { author: "Jean-Marc T.", rating: 4, text: "Très bon suivi pour mes implants. Résultat naturel et durable. Merci à toute l'équipe.", date: "Il y a 2 mois" },
  { author: "Sophie B.", rating: 5, text: "Mon fils de 5 ans adore y aller ! L'approche avec les enfants est formidable.", date: "Il y a 2 mois" },
  { author: "Laurent M.", rating: 5, text: "Enfin un cabinet qui prend le temps. Les explications sont claires et les soins de qualité.", date: "Il y a 3 mois" },
  { author: "Claire V.", rating: 5, text: "Blanchiment réussi ! Résultat naturel, je suis ravie. Équipe au top.", date: "Il y a 3 mois" },
  { author: "François G.", rating: 4, text: "Bonne prise en charge d'urgence un samedi matin. Réactif et efficace.", date: "Il y a 4 mois" },
];

export const FAQ_ITEMS = [
  { q: "Est-ce que les soins dentaires font mal ?", a: "La grande majorité des soins sont réalisés sous anesthésie locale et sont totalement indolores. Notre priorité est votre confort. N'hésitez pas à nous signaler toute appréhension." },
  { q: "À quelle fréquence dois-je consulter ?", a: "Nous recommandons une visite de contrôle tous les 6 mois à 1 an. Un suivi régulier permet de détecter et traiter les problèmes à un stade précoce." },
  { q: "Acceptez-vous les urgences ?", a: "Oui, nous réservons des créneaux pour les urgences dentaires. Appelez-nous directement par téléphone pour une prise en charge rapide." },
  { q: "Êtes-vous conventionné ?", a: "Oui, notre cabinet est conventionné secteur 1. La plupart des soins courants sont pris en charge par l'Assurance Maladie et votre mutuelle." },
  { q: "Comment se déroule une première consultation ?", a: "La première consultation dure environ 45 minutes. Elle comprend un échange sur vos attentes, un examen clinique complet, des radiographies si nécessaire, et l'élaboration d'un plan de traitement personnalisé." },
  { q: "Proposez-vous le paiement en plusieurs fois ?", a: "Oui, nous proposons des facilités de paiement pour les traitements importants. N'hésitez pas à nous en parler lors de votre consultation." },
  { q: "Les implants dentaires sont-ils remboursés ?", a: "Les implants ne sont pas remboursés par l'Assurance Maladie, mais de nombreuses mutuelles proposent une prise en charge partielle. Nous vous fournirons un devis détaillé." },
  { q: "À partir de quel âge emmener mon enfant chez le dentiste ?", a: "Nous recommandons une première visite dès l'âge de 3 ans, ou dès l'apparition des premières dents de lait si vous avez des inquiétudes." },
  { q: "Quels moyens de paiement acceptez-vous ?", a: "Nous acceptons les cartes bancaires, les chèques, les espèces et la télétransmission avec votre carte Vitale." },
  { q: "Le cabinet est-il accessible aux personnes à mobilité réduite ?", a: "Oui, notre cabinet est entièrement accessible aux personnes à mobilité réduite (PMR). Un accès de plain-pied et des équipements adaptés sont à votre disposition." },
];

export const BLOG_ARTICLES = [
  {
    id: "bien-se-brosser-les-dents",
    title: "Comment bien se brosser les dents ?",
    excerpt: "Découvrez les techniques de brossage recommandées par nos dentistes pour une hygiène bucco-dentaire optimale.",
    content: `Le brossage des dents est le geste fondamental de l'hygiène bucco-dentaire. Pourtant, beaucoup de personnes ne le réalisent pas correctement.\n\n La technique recommandée\n\nUtilisez une brosse à dents souple et un dentifrice fluoré. Placez la brosse à 45° par rapport à la gencive et effectuez des mouvements circulaires doux, de la gencive vers la dent.\n\n Durée et fréquence\n\nBrossez-vous les dents pendant **2 minutes minimum**, au moins **2 fois par jour** (matin et soir). Le brossage du soir est le plus important.\n\n N'oubliez pas\n\n- Changez de brosse à dents tous les 3 mois\n- Utilisez du fil dentaire ou des brossettes interdentaires\n- Complétez avec un bain de bouche si recommandé par votre dentiste`,
    category: "Hygiène",
    readTime: "3 min",
  },
  {
    id: "frequence-consultation",
    title: "À quelle fréquence consulter son dentiste ?",
    excerpt: "Un suivi régulier est essentiel pour prévenir les problèmes dentaires. Voici nos recommandations.",
    content: "Un suivi dentaire régulier est la clé d'une bonne santé bucco-dentaire...",
    category: "Prévention",
    readTime: "4 min",
  },
  {
    id: "sensibilite-dentaire",
    title: "Sensibilité dentaire : causes et solutions",
    excerpt: "Douleur au chaud, au froid ? La sensibilité dentaire touche de nombreuses personnes. Découvrez comment y remédier.",
    content: "La sensibilité dentaire se manifeste par une douleur vive et brève...",
    category: "Soins",
    readTime: "5 min",
  },
  {
    id: "dents-de-sagesse",
    title: "Dents de sagesse : faut-il les extraire ?",
    excerpt: "Les dents de sagesse posent souvent problème. Découvrez quand et pourquoi il peut être nécessaire de les retirer.",
    content: "Les dents de sagesse apparaissent généralement entre 17 et 25 ans...",
    category: "Chirurgie",
    readTime: "4 min",
  },
  {
    id: "gingivite",
    title: "Gingivite : comment la reconnaître et la traiter ?",
    excerpt: "Gencives rouges, gonflées ou qui saignent ? Il s'agit peut-être d'une gingivite. Voici comment agir.",
    content: "La gingivite est une inflammation des gencives causée par l'accumulation de plaque dentaire...",
    category: "Parodontologie",
    readTime: "4 min",
  },
  {
    id: "blanchiment-dentaire",
    title: "Blanchiment dentaire : ce qu'il faut savoir",
    excerpt: "Envie d'un sourire plus blanc ? Découvrez les options de blanchiment sûres et efficaces.",
    content: "Le blanchiment dentaire est un traitement esthétique très demandé...",
    category: "Esthétique",
    readTime: "5 min",
  },
  {
    id: "implants-dentaires-guide",
    title: "Guide complet des implants dentaires",
    excerpt: "Tout ce que vous devez savoir sur les implants : procédure, durée, coût et résultats.",
    content: "L'implant dentaire est considéré comme la meilleure solution pour remplacer une dent manquante...",
    category: "Implantologie",
    readTime: "6 min",
  },
  {
    id: "soins-dentaires-enfants",
    title: "Soins dentaires pour les enfants : guide pour les parents",
    excerpt: "Comment prendre soin des dents de votre enfant dès le plus jeune âge.",
    content: "La santé bucco-dentaire de votre enfant se construit dès les premiers mois de vie...",
    category: "Pédodontie",
    readTime: "5 min",
  },
];

export const TECHNOLOGIES = [
  { title: "Radio numérique", description: "Radiographies instantanées avec 90% moins de radiation qu'une radio traditionnelle.", benefit: "Diagnostic rapide et précis" },
  { title: "Caméra intra-orale", description: "Visualisez en temps réel l'état de vos dents sur un écran haute définition.", benefit: "Meilleure compréhension du diagnostic" },
  { title: "Empreinte optique 3D", description: "Fini la pâte d'empreinte ! Scanner numérique pour un confort optimal.", benefit: "Confort et précision accrus" },
  { title: "Scanner 3D (CBCT)", description: "Imagerie 3D pour une planification précise des implants et traitements complexes.", benefit: "Sécurité et précision maximales" },
  { title: "Stérilisation haute performance", description: "Protocole de stérilisation rigoureux avec autoclaves de classe B.", benefit: "Sécurité sanitaire garantie" },
  { title: "Équipements dernière génération", description: "Fauteuils ergonomiques, éclairage LED, et instruments de dernière technologie.", benefit: "Confort et performance" },
];
